### block_api.get_block

POST http://localhost:3000 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "block_api.get_block",
  "params": { "block_num": 2 },
  "id": 3
}

### block_api.get_block_range

POST http://localhost:3000 HTTP/1.1

{
  "jsonrpc":"2.0", 
  "method":"block_api.get_block_range",
  "params": {
    "starting_block_num": 0,
    "count": 1
  }, 
  "id":1
}
