### condenser_api_get_accounts

POST http://localhost:3000 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "rc_api.find_rc_accounts",
  "params": ["boby"],
  "id": 1
}
