name: go-mimic CI
on:
  push:
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23.0, 1.24.0]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go version ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run format checking
        run: gofmt -d -e -l -s .
      - name: Run tests
        run: go test ./... -v -count=1
      - name: Run build go-mimic
        run: go build ./cmd/main.go
